apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: ALLOWED_HOSTS
              value: localhost,api,34.172.138.181
            - name: CELERY_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  key: CELERY_BROKER_URL
                  name: backend-env
            - name: DASHBOARD_URL
              value: http://localhost:9002/
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_URL
                  name: backend-env
            - name: DEFAULT_CHANNEL_SLUG
              valueFrom:
                configMapKeyRef:
                  key: DEFAULT_CHANNEL_SLUG
                  name: common-env
            - name: DEFAULT_FROM_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: DEFAULT_FROM_EMAIL
                  name: backend-env
            - name: EMAIL_URL
              valueFrom:
                configMapKeyRef:
                  key: EMAIL_URL
                  name: backend-env
            - name: HTTP_IP_FILTER_ALLOW_LOOPBACK_IPS
              valueFrom:
                configMapKeyRef:
                  key: HTTP_IP_FILTER_ALLOW_LOOPBACK_IPS
                  name: common-env
            - name: HTTP_IP_FILTER_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: HTTP_IP_FILTER_ENABLED
                  name: common-env
            - name: JAEGER_AGENT_HOST
              value: jaeger
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: SECRET_KEY
                  name: backend-env
          image: ghcr.io/saleor/saleor:3.20
          name: api
          ports:
            - containerPort: 8000
              protocol: TCP
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/db
              name: saleor-db
            - mountPath: /docker-entrypoint-initdb.d/replica_user.sq
              name: api-cm1
              subPath: replica_user.sq
      restartPolicy: Always
      volumes:
        - name: saleor-db
          persistentVolumeClaim:
            claimName: saleor-db
        - configMap:
            items:
              - key: replica_user.sql
                path: replica_user.sq
            name: api-cm1
          name: api-cm1
