apiVersion: v1
data:
  CELERY_BROKER_URL: redis://redis:6379/1
  DATABASE_URL: postgres://saleor:saleor@db/saleor
  DEFAULT_FROM_EMAIL: noreply@example.com
  EMAIL_URL: smtp://mailpit:1025
  SECRET_KEY: changeme
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: api-backend-env
  name: backend-env
