services:
  api:
    image: ghcr.io/saleor/saleor:3.20
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
      - jaeger
    volumes:
      # Shared volume between worker and api for media
      - saleor-media:/app/media
    env_file:
      - common.env
      - backend.env
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - DASHBOARD_URL=http://localhost:9000/
      - ALLOWED_HOSTS=localhost,api
    deploy:
      resources:
        limits:
          cpus: '0.50'       # Maximum 50% of CPU
          memory: '512M'     # Maximum 512MB of RAM
        reservations:
          cpus: '0.25'       # Reserve 25% of CPU
          memory: '256M'     # Reserve 256MB of RAM
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5

  dashboard:
    image: ghcr.io/saleor/saleor-dashboard:latest
    ports:
      - 9002:80
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    deploy:
      resources:
        limits:
          cpus: '0.25'       # Maximum 25% of CPU
          memory: '256M'     # Maximum 256MB of RAM
        reservations:
          cpus: '0.10'       # Reserve 10% of CPU
          memory: '128M'     # Reserve 128MB of RAM
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: library/postgres:15-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-db:/var/lib/postgresql/data
      - ./replica_user.sql:/docker-entrypoint-initdb.d/replica_user.sql
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor
    deploy:
      resources:
        limits:
          cpus: '0.50'       # Limit for the database
          memory: '512M'     # Maximum 512MB of RAM

  redis:
    image: library/redis:7.0-alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-redis:/data
    deploy:
      resources:
        limits:
          cpus: '0.10'       # Redis resource limit
          memory: '128M'     # Maximum 128MB of RAM

  worker:
    image: ghcr.io/saleor/saleor:3.20
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -B
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    env_file:
      - common.env
      - backend.env
    depends_on:
      - redis
      - mailpit
    volumes:
      # Shared volume between worker and api for media
      - saleor-media:/app/media
    deploy:
      resources:
        limits:
          cpus: '0.25'       # Limit for worker
          memory: '512M'     # Maximum 256MB of RAM

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - type: tmpfs
        target: /tmp
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: '128M'

  mailpit:
    image: axllent/mailpit
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui. Visit http://localhost:8025/ to check emails
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: '64M'

volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local
  saleor-media:

networks:
  saleor-backend-tier:
    driver: bridge
