apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mailpit
  name: mailpit
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mailpit
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: mailpit
    spec:
      containers:
        - image: axllent/mailpit
          name: mailpit
          ports:
            - containerPort: 1025
              protocol: TCP
            - containerPort: 8025
              protocol: TCP
      restartPolicy: Always
