apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: saleor-db
  name: saleor-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Increased to 1Gi for more storage
  storageClassName: standard-rwo
